# Generated by Django 3.2.25 on 2025-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
