# Generated by Django 3.2.25 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pha_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('licence', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('repass', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
    ]
