# Generated by Django 3.2.25 on 2025-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ch_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('chat', models.CharField(max_length=500)),
                ('to_type', models.CharField(max_length=30)),
                ('from_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
    ]
