# Generated by Django 3.2.25 on 2025-05-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(db_column='doc_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('hospital', models.ForeignKey(db_column='h_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('patient', models.ForeignKey(db_column='p_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
