# Generated by Django 3.2.25 on 2025-06-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
