# Generated by Django 3.2.25 on 2025-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('p_id', models.IntegerField()),
                ('dose', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('medname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
    ]
