# Generated by Django 3.2.25 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryagent',
            fields=[
                ('da_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phno', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=200)),
                ('pha_id', models.IntegerField()),
            ],
            options={
                'db_table': 'deliveryagent',
                'managed': False,
            },
        ),
    ]
