# Generated by Django 3.2.25 on 2025-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('mfd', models.DateField()),
                ('exd', models.DateField()),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
    ]
