# Generated by Django 3.2.25 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalname', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('repass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
    ]
