# Generated by Django 3.2.25 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=30)),
                ('doc_age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('specilization', models.CharField(max_length=30)),
                ('cousulting_hour', models.CharField(max_length=20)),
                ('deparment', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
